name = "moddable-tools"
main = "index.js"
compatibility_date = "2024-01-01"
workers_dev = true

[vars]
ALLOWED_ORIGINS = "https://moddable.games,https://chess.moddable.games,https://hex.moddable.games,https://tools.moddable.games"

[[routes]]
pattern = "tools.moddable.games/*"
zone_name = "moddable.games"

[[durable_objects.bindings]]
name = "GAME_ROOMS"
class_name = "GameRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]
