name = "moddable-api"
main = "index.js"
compatibility_date = "2024-01-01"

[vars]
ALLOWED_ORIGIN = "https://web.moddable.games"

[[kv_namespaces]]
binding = "STORE"
id = "01d09ee59d5a41e0a43cd60eedb9d345"
