name = "moddable-api"
main = "index.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "moddable.games/api/*", zone_name = "moddable.games" },
  { pattern = "www.moddable.games/api/*", zone_name = "moddable.games" }
]

[vars]
ALLOWED_ORIGIN = "https://moddable.games"

[[kv_namespaces]]
binding = "STORE"
id = "01d09ee59d5a41e0a43cd60eedb9d345"
